id: PF6D553C9
initial_creation_type: ocr
source_metadata:
  volumes:
    8572d12594634e9a8c19e419ff1136e4:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: འཁོར་བ་ལས་ཡིད་ངེས་པར་འབྱུང་བར་བྱེད་པ་ཞེས་བྱ་བའི་གླུ།
      total_pages: 1902
      volume_number: 26
